/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Data;
import Model.BiodataL;
import Model.TBooking;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadila Mazaya Asriel
 */
public class Biodata extends javax.swing.JFrame {
    private final DefaultTableModel model = new DefaultTableModel();
    private Data koneksiData = new Data();
    /**
     * Creates new form Vip
     */
    public Biodata() {
        initComponents();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        // Matiin Resize / Maximize
        setResizable(false);
        inputId.setEditable(true);
        
        model.addColumn("ID");
        model.addColumn("Fullname");
        model.addColumn("Birthdate");
        model.addColumn("Age");
        model.addColumn("Address");
        model.addColumn("City");
        model.addColumn("Contact");

        tblCustomer.setModel(model);
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        inputId = new javax.swing.JTextField();
        inputBirthdate = new javax.swing.JTextField();
        inputAge = new javax.swing.JTextField();
        inputAddress = new javax.swing.JTextField();
        inputCity = new javax.swing.JTextField();
        inputContact = new javax.swing.JTextField();
        inputFullname = new javax.swing.JTextField();
        customerList = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        birthdate = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        biodata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(184, 218, 252));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 460));
        jPanel1.setLayout(null);

        btnHapus.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);
        btnHapus.setBounds(962, 453, 90, 30);

        btnSubmit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(260, 420, 72, 30);

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(10, 453, 80, 30);

        btnQuit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuit);
        btnQuit.setBounds(420, 450, 80, 30);

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Birthdate", "Age", "Address", "City", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCustomer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(510, 170, 630, 220);

        inputId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputIdActionPerformed(evt);
            }
        });
        jPanel1.add(inputId);
        inputId.setBounds(240, 170, 180, 30);
        jPanel1.add(inputBirthdate);
        inputBirthdate.setBounds(240, 210, 180, 30);
        jPanel1.add(inputAge);
        inputAge.setBounds(240, 250, 180, 30);

        inputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressActionPerformed(evt);
            }
        });
        jPanel1.add(inputAddress);
        inputAddress.setBounds(240, 290, 180, 30);

        inputCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCityActionPerformed(evt);
            }
        });
        jPanel1.add(inputCity);
        inputCity.setBounds(240, 330, 180, 30);

        inputContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputContactActionPerformed(evt);
            }
        });
        jPanel1.add(inputContact);
        inputContact.setBounds(240, 370, 180, 30);

        inputFullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFullnameActionPerformed(evt);
            }
        });
        jPanel1.add(inputFullname);
        inputFullname.setBounds(240, 130, 180, 30);

        customerList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        customerList.setText("Customer List");
        jPanel1.add(customerList);
        customerList.setBounds(540, 120, 210, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desain tanpa judul (24).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(890, 340, 310, 250);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desain tanpa judul (22)_1.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(1000, 0, 170, 500);

        name.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        name.setText("Name :");
        jPanel1.add(name);
        name.setBounds(120, 130, 70, 25);

        id.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        id.setText("ID :");
        jPanel1.add(id);
        id.setBounds(120, 170, 70, 25);

        birthdate.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        birthdate.setText("Birthdate :");
        jPanel1.add(birthdate);
        birthdate.setBounds(120, 210, 90, 25);

        age.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        age.setText("Age :");
        jPanel1.add(age);
        age.setBounds(120, 250, 70, 30);

        address.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        address.setText("Address :");
        jPanel1.add(address);
        address.setBounds(120, 300, 100, 25);

        city.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        city.setText("City :");
        jPanel1.add(city);
        city.setBounds(120, 340, 80, 25);

        contact.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        contact.setText("Contact:");
        jPanel1.add(contact);
        contact.setBounds(120, 380, 70, 25);

        biodata.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        biodata.setText("Biodata");
        jPanel1.add(biodata);
        biodata.setBounds(120, 80, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desain tanpa judul (22)_1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desain tanpa judul (22)_1.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(500, 0, 580, 500);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
       private void populateTable() {
        model.setRowCount(0);
        try {
            ArrayList<BiodataL> lihat = koneksiData.tampilDataBiodata();
            for (BiodataL bl : lihat) {
                Object[] isiData = {bl.getId(), bl.getFullname(), bl.getBirthdate(), bl.getAge(), bl.getAddress(), bl.getCity(), bl.getContact()};
                model.addRow(isiData);
            }
        } catch (SQLException ex) {
            System.out.println("Eksepsi: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        }

    }
    
    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
      Menu menu = new Menu();
      menu.setVisible(true);
      this.dispose();
      
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
         String id = inputId.getText();
         String fullname = inputFullname.getText();
         String birthdate = inputBirthdate.getText();
         String age = inputAge.getText();
         String address = inputAddress.getText();
         String city = inputCity.getText();
         String contact = inputContact.getText();
         BiodataL bl = new BiodataL(id, fullname, birthdate, age, address, city, contact);

        if (fullname.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add Fullname!");
        } else if (id.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add id!");
        } else if(birthdate.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Add  Birthdate!");
        } else if (age.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add Age!");
        } else if (address.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add Address!");
        } else if (city.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add City!");
        } else if (contact.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Add Contact!");
        } else if (btnSubmit.getText().equals("Submit")) {
            try {
                if (koneksiData.tambahDataBiodata(bl)) {
                    JOptionPane.showMessageDialog(this, "Add Data Success !");
                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Add Data Failed !");
                }
            } catch (SQLException ex) {
                System.out.println("Eksepsi: " + ex.getMessage());
                JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
            }
    }//GEN-LAST:event_btnSubmitActionPerformed
    }
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = tblCustomer.getSelectedRow();
        String id = model.getValueAt(selectedRow, 0).toString();
        int jawaban = JOptionPane.showConfirmDialog(this, "Data Delete " + id + "?", "Delete", JOptionPane.YES_NO_OPTION);
        if (jawaban == JOptionPane.YES_OPTION) {
            //hapus
            try {
                if (koneksiData.hapusDataBiodata(id)) {
                    JOptionPane.showMessageDialog(this, "Delete Success");
                    populateTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Delete Failed");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Eksepsi: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void inputFullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFullnameActionPerformed

    private void inputIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputIdActionPerformed

    private void inputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressActionPerformed

    private void inputCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCityActionPerformed

    private void inputContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputContactActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JLabel biodata;
    private javax.swing.JLabel birthdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel city;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel customerList;
    private javax.swing.JLabel id;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputAge;
    private javax.swing.JTextField inputBirthdate;
    private javax.swing.JTextField inputCity;
    private javax.swing.JTextField inputContact;
    private javax.swing.JTextField inputFullname;
    private javax.swing.JTextField inputId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JTable tblCustomer;
    // End of variables declaration//GEN-END:variables
}
