/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Data;
import Model.TBooking;
import Model.TList;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadila Mazaya Asriel
 */
public class ListTicket extends javax.swing.JFrame {

    private DefaultTableModel model = null;
    private Data koneksiData = new Data();

    /**
     * Creates new form ListTicket
     */
    public ListTicket() {
        initComponents();

        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        setResizable(false);
        this.model = (DefaultTableModel) tblTicket.getModel();
        populateTable();
    }

    private void populateTable() {
        model.setRowCount(0);
        //Enkaptulasi
        try {
            ArrayList<TList> lihat = koneksiData.tampilDataTicket();
            for (TList tl : lihat) {
                Object[] isiData = {tl.getAirlines(), tl.getDepart(), tl.getArrive(), tl.getAvailable(), tl.getTime(), tl.getDate(), tl.getPrice(), tl.getTicketCode()};
                model.addRow(isiData);
            }
        } catch (SQLException ex) {
            System.out.println("Eksepsi: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnPesan1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(184, 218, 252));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Minion Pro SmBd", 0, 36)); // NOI18N
        jLabel1.setText("Ticket List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(610, 40, 230, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Teks paragraf Anda.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(-100, -40, 421, 420);

        tblTicket.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Garuda", "Jakarta", "Bengkuliu", "10", "10 A.M - 13 P.M", "23 Januari 2023", "Rp.1.500.000", "A1"},
                {"Garuda", "Jakarta", "Pekanbaru", "5", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "A2"},
                {"Garuda", "Jakarta", "Padang", "3", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "A3"},
                {"Garuda", "Jakarta", "Medan", "5", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "A4"},
                {"Lion", "Jakarta", "Bali", "4", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "B1"},
                {"Lion", "Jakarta", "Surabaya", "10", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "B2"},
                {"Lion", "Jakarta", "Yogyakarta", "10", "10 A.M -13 P.M", "23 Januari 2023", "Rp.Rp.1.500.000", "B3"}
            },
            new String [] {
                "Airlines", "Depart", "Arrive", "Available", "Time", "Date", "Price", "Code Ticket"
            }
        ));
        jScrollPane1.setViewportView(tblTicket);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 100, 780, 130);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack);
        btnBack.setBounds(310, 260, 80, 23);

        btnPesan1.setText("Book");
        btnPesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesan1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesan1);
        btnPesan1.setBounds(1000, 270, 72, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesan1ActionPerformed
        int selectedRow = tblTicket.getSelectedRow();
        String airlines = model.getValueAt(selectedRow, 0).toString();
        String depart = model.getValueAt(selectedRow, 1).toString();
        String arrive = model.getValueAt(selectedRow, 2).toString();
        String ticketCode = model.getValueAt(selectedRow, 7).toString();
        TicketBooking tb = new TicketBooking(airlines, depart, arrive, ticketCode);
        tb.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnPesan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPesan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTicket;
    // End of variables declaration//GEN-END:variables
}
