/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.Data;
import Model.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nadila Mazaya Asriel
 */
public class Register extends javax.swing.JFrame {
    private final DefaultTableModel model = new DefaultTableModel();
    private Data data = new Data();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Gambar = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputPassword = new javax.swing.JTextField();
        inputId = new javax.swing.JTextField();
        inputUsername = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        status = new javax.swing.JLabel();
        pilStatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(184, 218, 252));
        Background.setLayout(null);

        Register.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Register.setText("Register");
        Background.add(Register);
        Register.setBounds(680, 20, 110, 70);

        Email.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Email.setText("Email :");
        Background.add(Email);
        Email.setBounds(680, 180, 90, 25);

        ID.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ID.setText("ID:");
        Background.add(ID);
        ID.setBounds(680, 100, 90, 25);

        Password.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Password.setText("Password :");
        Background.add(Password);
        Password.setBounds(680, 260, 110, 25);

        Name.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Name.setText("Name:");
        Background.add(Name);
        Name.setBounds(680, 140, 90, 25);

        Username.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        Username.setText("Username :");
        Background.add(Username);
        Username.setBounds(680, 220, 100, 30);

        Gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Desain tanpa judul (6).png"))); // NOI18N
        Background.add(Gambar);
        Gambar.setBounds(-160, -10, 770, 540);
        Background.add(inputName);
        inputName.setBounds(790, 140, 140, 30);
        Background.add(inputEmail);
        inputEmail.setBounds(790, 180, 140, 30);

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        Background.add(inputPassword);
        inputPassword.setBounds(790, 260, 140, 30);
        Background.add(inputId);
        inputId.setBounds(790, 100, 140, 30);
        Background.add(inputUsername);
        inputUsername.setBounds(790, 220, 140, 30);

        btnRegister.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        Background.add(btnRegister);
        btnRegister.setBounds(850, 370, 90, 30);

        btnBack.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        Background.add(btnBack);
        btnBack.setBounds(740, 370, 90, 30);

        status.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        status.setText("Status :");
        Background.add(status);
        status.setBounds(680, 310, 90, 25);

        pilStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        Background.add(pilStatus);
        pilStatus.setBounds(790, 310, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 963, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void populateTable() {
        model.setRowCount(0);
        try {
            ArrayList<User> lihat = data.tampilDataUsers();
            for (User a : lihat) {
                Object[] isiData = {a.getId(), a.getName(), a.getEmail(), a.getUsername(), a.getPassword()};
                model.addRow(isiData);
            }
        } catch (SQLException ex) {
            System.out.println("Eksepsi: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
        }

    }
    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String id = inputId.getText();
        String name = inputName.getText();
        String email = inputEmail.getText();
        String username = inputUsername.getText();
        String password = inputPassword.getText();
        String status = pilStatus.getSelectedItem().toString();
        
        User user = new User(id, name, email,  username, password, status);
        
        if (id.equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Add id!");
        }else if(name.equals("")){
             JOptionPane.showMessageDialog(rootPane, "Add username !");
        }else if(username.equals("")){
             JOptionPane.showMessageDialog(rootPane, "Add username !");
        }else if (email.equals("")) {
             JOptionPane.showMessageDialog(rootPane, "Add email !");
        }else if (password.equals("")) {
             JOptionPane.showMessageDialog(rootPane, " Add password !");
        }else if (btnRegister.getText().equals("Register")) {
             try{
                 if (data.tambahDataUsers(user)) {
                     JOptionPane.showMessageDialog(this, "Success Register");
                     Login log = new Login();
                     log.setVisible(true);
                     this.dispose();
                       
                 }else{
                     JOptionPane.showMessageDialog(this, "Invalid Register");
                 }
                 
             }catch(SQLException ex){
                 System.out.println("Eksepsi: " + ex.getMessage());
                 JOptionPane.showMessageDialog(null, "Exception: " + ex.getMessage());
             }
             
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Welcome come = new Welcome();
        come.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

//    private void goToLogin() {
//    }
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Gambar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel Username;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JComboBox<String> pilStatus;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
